### ISSUE TITLE
Wrong Theme Name

### ISSUE THREAD

**Issue by luveti** [rexebin/dracula#2]
I believe the theme you're emulating here is called **Darcula**. Like so:

![screen shot 2018-11-30 at 11 26 35](https://user-images.githubusercontent.com/4952718/49301652-1dac4880-f493-11e8-8c6b-01f4b7dad70c.png)

This is what the **Dracula** theme looks like:
![screen shot 2018-11-30 at 11 29 22](https://user-images.githubusercontent.com/4952718/49301693-34eb3600-f493-11e8-97af-879dbcc3f8a0.png)

And there is already an official theme for it: https://marketplace.visualstudio.com/items?itemName=dracula-theme.theme-dracula

Love the theme though! It looks really nice :)

**Comment by rexebin** [comment]
I was wondering why the Dracula themes in the market have nothing in common with the same webstorm “Dracula” theme..🤣 What a genius name the JetBrains teams came up! I googled it, only the theme came up otherwise it is not a word, which makes it completely unique to the theme.

Thank you for taking time letting me know. I am grateful. 

Let’s see how to go about changing an extension’s name.

I am happy you liked the theme. If you see any wrong colour, please let me know.
